<a href="https://colab.research.google.com/github/dima1115/Machine-learning/blob/main/%D0%94%D0%B0%D1%80%D0%BC%D0%BE%D1%81%D1%82%D1%83%D0%BA_%D0%BF%D1%801_6.ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1
Тема: Вступ до машинного навчання. Елементи лінійної алгебри  
Варіант: 6  
Формат: Google Colab (.ipynb)  
Автор: Дармостук Дмитро (приклад заповнення; за потреби замініть на власні дані)

Нагадування вимог (з файлу): Кожне завдання супроводжується назвою як коментарем; у кінці — висновок.

У цьому зошиті реалізовано усі 15 завдань для варіанту 6 — тобто пункт №6 в кожному з 15 блоків.


In [6]:

# === Налаштування довкілля та допоміжні функції ===
import numpy as np

np.random.seed(6)  # фіксуємо зерно випадковості для відтворюваності

def pretty(a):
    """Акуратний друк векторів/матриць."""
    a = np.array(a)
    if a.ndim == 1:
        print(a)
    else:
        for row in a:
            print(row)



In [7]:
# Завдання 1, пункт 6 (варіант 6)
# Створіть одновимірний масив (вектор) з перших 10-ти додатних парних чисел та виведіть його значення.
vec_1_6 = np.arange(2, 2*10+1, 2)
pretty(vec_1_6)

[ 2  4  6  8 10 12 14 16 18 20]


In [8]:
# Завдання 2, пункт 6 (варіант 6)
# Створіть матрицю 3x3, заповніть її сумою кожного числа та його попереднього, починаючи з 1, і виведіть.
# Інтерпретація послідовності: a_n = n + (n-1) при n>=1 (тобто 1,3,5,7,...) заповнюємо построково.
seq = np.array([2*n-1 for n in range(1, 9+1)])  # 9 елементів для 3x3
mat_2_6 = seq.reshape(3,3)
pretty(mat_2_6)

[1 3 5]
[ 7  9 11]
[13 15 17]


In [9]:
# Завдання 3, пункт 6 (варіант 6)
# Масив 2x3 з випадкових цілих чисел у діапазоні від -1 до 1.
mat_3_6 = np.random.randint(-1, 2, size=(2,3))
pretty(mat_3_6)

[ 1  0 -1]
[1 0 1]


In [10]:
# Завдання 4, пункт 6 (варіант 6)
# Масив 5x5 з випадкових дійсних чисел у [0,1]; вектор-стовпчик сум елементів кожного рядка.
mat_4_6 = np.random.rand(5,5)
sums_rows = mat_4_6.sum(axis=1).reshape(-1,1)
print("Матриця 5x5:")
pretty(mat_4_6)
print("\nВектор-стовпчик сум рядків:")
pretty(sums_rows)

Матриця 5x5:
[0.10765668 0.59505206 0.52981736 0.41880743 0.33540785]
[0.62251943 0.43814143 0.73588211 0.51803641 0.5788586 ]
[0.6453551  0.99022427 0.8198582  0.41320093 0.87626766]
[0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
[0.70913175 0.54093685 0.12482417 0.9576473  0.4032563 ]

Вектор-стовпчик сум рядків:
[1.98674138]
[2.89343798]
[3.74490615]
[3.13544838]
[2.73579637]


In [11]:
# Завдання 5, пункт 6 (варіант 6)
# Два вектори розміром 5 з випадкових дійсних у [0,1]; поелементно: +, -, *.
a_5_6 = np.random.rand(5)
b_5_6 = np.random.rand(5)
print("a =", a_5_6)
print("b =", b_5_6)
print("a + b =", a_5_6 + b_5_6)
print("a - b =", a_5_6 - b_5_6)
print("a * b =", a_5_6 * b_5_6)

a = [0.21695116 0.71727585 0.99420744 0.25561406 0.67130943]
b = [0.59900591 0.71733215 0.93734953 0.35180977 0.2536341 ]
a + b = [0.81595707 1.43460799 1.93155697 0.60742382 0.92494353]
a - b = [-3.82054753e-01 -5.62991022e-05  5.68579038e-02 -9.61957129e-02
  4.17675334e-01]
a * b = [0.12995503 0.51452502 0.93191988 0.08992752 0.17026696]


In [12]:
# Завдання 6, пункт 6 (варіант 6)
# Дві матриці 3x3 з дійсних у [5,30]; знайти їх добуток.
A_6_6 = 5 + (30-5)*np.random.rand(3,3)
B_6_6 = 5 + (30-5)*np.random.rand(3,3)
C_6_6 = A_6_6 @ B_6_6
print("A:")
pretty(A_6_6)
print("\nB:")
pretty(B_6_6)
print("\nA @ B:")
pretty(C_6_6)

A:
[15.06181273 23.66276793 23.10176419]
[15.1526949  29.73449621 16.26248202]
[14.34521085 22.74071515  7.06146383]

B:
[14.95932297 24.27202416 24.11877459]
[12.09648459  9.73855476 16.78127412]
[13.37015111 23.36837609  9.72767789]

A @ B:
[ 820.4249068  1135.87255747  985.09038169]
[ 803.78877408 1037.38539227 1022.64335109]
[584.09019114 734.66394676 796.2987272 ]


In [13]:
# Завдання 7, пункт 6 (варіант 6)
# Дві матриці 2x3 та 3x4 з цілих у [1,5]; перемножити.
A_7_6 = np.random.randint(1,6,size=(2,3))
B_7_6 = np.random.randint(1,6,size=(3,4))
C_7_6 = A_7_6 @ B_7_6
print("A (2x3):")
pretty(A_7_6)
print("\nB (3x4):")
pretty(B_7_6)
print("\nA @ B (2x4):")
pretty(C_7_6)

A (2x3):
[2 4 4]
[2 5 2]

B (3x4):
[1 5 3 3]
[3 5 3 2]
[5 3 3 4]

A @ B (2x4):
[34 42 30 30]
[27 41 27 24]


In [14]:
# Завдання 8, пункт 6 (варіант 6)
# Матриця 3x3 з цілих у [1,8]; знайти обернену матрицю (генеруємо, поки матриця невироджена).
def random_invertible_int_matrix(low, high, size):
    while True:
        M = np.random.randint(low, high+1, size=size)
        if np.linalg.det(M) != 0:
            return M

M_8_6 = random_invertible_int_matrix(1,8,(3,3))
M_inv_8_6 = np.linalg.inv(M_8_6)
print("M:")
pretty(M_8_6)
print("\nM^{-1}:")
pretty(M_inv_8_6)
print("\nПеревірка M @ M^{-1} (≈ I):")
pretty(M_8_6 @ M_inv_8_6)

M:
[5 5 8]
[7 7 5]
[7 6 8]

M^{-1}:
[-0.83870968 -0.25806452  1.        ]
[ 0.67741935  0.51612903 -1.        ]
[ 2.25806452e-01 -1.61290323e-01  2.00556417e-16]

Перевірка M @ M^{-1} (≈ I):
[ 1.00000000e+00 -4.44089210e-16  8.27295222e-16]
[5.55111512e-17 1.00000000e+00 4.47670574e-16]
[0. 0. 1.]


In [15]:
# Завдання 9, пункт 6 (варіант 6)
# Матриця 4x4 з дійсних у [0,1]; транспонувати.
M_9_6 = np.random.rand(4,4)
print("M:")
pretty(M_9_6)
print("\nM^T:")
pretty(M_9_6.T)

M:
[0.40510246 0.14829153 0.68228713 0.16348875]
[0.64822524 0.25161414 0.0413755  0.9587226 ]
[0.06622048 0.51294019 0.34129659 0.66000982]
[0.84442734 0.60386656 0.58721369 0.11703304]

M^T:
[0.40510246 0.64822524 0.06622048 0.84442734]
[0.14829153 0.25161414 0.51294019 0.60386656]
[0.68228713 0.0413755  0.34129659 0.58721369]
[0.16348875 0.9587226  0.66000982 0.11703304]


In [16]:
# Завдання 10, пункт 6 (варіант 6)
# Матриця 3x4 і вектор 4x1, обидва з дійсних у [0,1]; знайти добуток.
A_10_6 = np.random.rand(3,4)
v_10_6 = np.random.rand(4,1)
prod_10_6 = A_10_6 @ v_10_6
print("A (3x4):")
pretty(A_10_6)
print("\nv (4x1):")
pretty(v_10_6)
print("\nA @ v (3x1):")
pretty(prod_10_6)

A (3x4):
[0.71045034 0.20452326 0.49036779 0.03660853]
[0.31540358 0.86303041 0.55846662 0.54670783]
[0.36782466 0.82815669 0.27635046 0.12565834]

v (4x1):
[0.56278108]
[0.26733901]
[0.77503493]
[0.17940635]

A @ v (3x1):
[0.84112502]
[0.93913884]
[0.66512851]


In [17]:
# Завдання 11, пункт 6 (варіант 6)
# Матриця 2x3 з цілих у [1,10] і вектор 3x1 з дійсних у [0,1]; добуток.
A_11_6 = np.random.randint(1,11,size=(2,3))
v_11_6 = np.random.rand(3,1)
prod_11_6 = A_11_6 @ v_11_6
print("A (2x3):")
pretty(A_11_6)
print("\nv (3x1):")
pretty(v_11_6)
print("\nA @ v (2x1):")
pretty(prod_11_6)

A (2x3):
[8 1 4]
[6 4 3]

v (3x1):
[0.75953865]
[0.63878662]
[0.5644305]

A @ v (2x1):
[8.97281783]
[8.80566989]


In [18]:
# Завдання 12, пункт 6 (варіант 6)
# Дві матриці 7x7 з цілих у [1,10]; знайти їхню різницю A - B.
A_12_6 = np.random.randint(1,11,size=(7,7))
B_12_6 = np.random.randint(1,11,size=(7,7))
D_12_6 = A_12_6 - B_12_6
print("A:")
pretty(A_12_6)
print("\nB:")
pretty(B_12_6)
print("\nA - B:")
pretty(D_12_6)

A:
[10  1  9  7  4  3  2]
[ 7  9  9 10  1  8  7]
[ 1  2  9  6 10  9  6]
[10  2  2  3 10 10  6]
[7 5 1 5 3 7 3]
[ 2 10  3  1  3  3  6]
[ 1  8  7  7  1 10  6]

B:
[ 5  9  3  5  3  4 10]
[5 1 6 8 7 2 2]
[ 8  2  7  9  2  6 10]
[3 3 5 9 8 2 6]
[4 5 7 5 6 7 9]
[ 6 10  8  1  4  5  7]
[3 8 7 1 6 9 9]

A - B:
[ 5 -8  6  2  1 -1 -8]
[ 2  8  3  2 -6  6  5]
[-7  0  2 -3  8  3 -4]
[ 7 -1 -3 -6  2  8  0]
[ 3  0 -6  0 -3  0 -6]
[-4  0 -5  0 -1 -2 -1]
[-2  0  0  6 -5  1 -3]


In [19]:
# Завдання 13, пункт 6 (варіант 6)
# Дві матриці 7x7 з цілих у [-10,10]; знайти суму їх елементів (окремо та разом).
A_13_6 = np.random.randint(-10,11,size=(7,7))
B_13_6 = np.random.randint(-10,11,size=(7,7))
sumA = A_13_6.sum()
sumB = B_13_6.sum()
print("A:")
pretty(A_13_6)
print("\nB:")
pretty(B_13_6)
print(f"\nСума елементів A: {sumA}")
print(f"Сума елементів B: {sumB}")
print(f"Загальна сума: {sumA + sumB}")

A:
[ 0 -4 -9  4 -5  0  1]
[ 0  1  2  8 -9 -3  8]
[ -3 -10  -5  -5  -2   3   0]
[-7 -6 -3 -1 -8  0  7]
[ 8  9  9  8  3  5 -9]
[-10  -5  -6   2  -7  10   6]
[10  7 -2  8 10  9 -5]

B:
[10 -5  5 -5 -4  5  0]
[ 9 -7 -8 -8 10 -5  7]
[-7  7  2 -3 10  9  8]
[ -3  10   5  -1   6  -6 -10]
[ 0  6 10  2 -6  9 10]
[-1  1  1 -6 -3  6  0]
[ 4 -5 -8 -9  7  7  4]

Сума елементів A: 14
Сума елементів B: 60
Загальна сума: 74


In [20]:
# Завдання 14, пункт 6 (варіант 6)
# Матриця 3x3 з цілих у [1,10]; знайти середнє арифметичне елементів.
M_14_6 = np.random.randint(1,11,size=(3,3))
mean_14_6 = M_14_6.mean()
pretty(M_14_6)
print("\nСереднє арифметичне:", mean_14_6)

[7 8 7]
[5 4 2]
[ 1 10  7]

Середнє арифметичне: 5.666666666666667


In [21]:
# Завдання 15, пункт 6 (варіант 6)
# Матриця 8x8 з дійсних у [-1,1]; вектор-стовпчик найменших елементів у кожному рядку.
M_15_6 = -1 + 2*np.random.rand(8,8)
mins_by_row = M_15_6.min(axis=1).reshape(-1,1)
print("Матриця 8x8:")
pretty(M_15_6)
print("\nВектор-стовпчик мінімумів по рядках:")
pretty(mins_by_row)

Матриця 8x8:
[ 0.67652879  0.59530143  0.12540379  0.89084722 -0.66627878 -0.45238534
 -0.86406041  0.36104624]
[-0.67660816 -0.30265084 -0.6695911  -0.28989051 -0.31625224 -0.47620078
  0.9182577   0.69900469]
[ 0.1409777  -0.97899623  0.11049714  0.97969793  0.70942008 -0.41745424
 -0.03238469 -0.1713275 ]
[-0.12473643 -0.90836169 -0.20985642 -0.11282154 -0.68618735 -0.64191533
  0.7120876  -0.50909295]
[ 0.07718658 -0.52704308 -0.89914252  0.92911922  0.82142729 -0.28822553
 -0.77123113 -0.16090328]
[-0.63431352  0.28472939  0.54229553  0.52253562 -0.8699674   0.24454314
 -0.04879747  0.21048352]
[-0.13893256  0.79906647 -0.65432815 -0.4841909  -0.59108494  0.47810942
 -0.6459847  -0.23173337]
[-0.37702239  0.5399199  -0.99896168  0.50278821  0.78169869 -0.18656783
  0.26299629  0.68922369]

Вектор-стовпчик мінімумів по рядках:
[-0.86406041]
[-0.67660816]
[-0.97899623]
[-0.90836169]
[-0.89914252]
[-0.8699674]
[-0.65432815]
[-0.99896168]


## Висновок
У зошиті реалізовано всі 15 завдань для варіанту 6 (пункт 6 у кожному розділі):
- Показано роботу з векторами, матрицями, базові операції (сума, різниця, множення),
- Роботу з транспонуванням, оберненою матрицею, агрегуванням по рядках/стовпцях,
- А також обчислення середніх значень, мінімумів, тощо. Випадковість фіксовано через `np.random.seed(6)` для відтворюваності результатів.

